apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-static-test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: "efs-static-test"
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: efs-static-test
  labels:
    purpose: "efs-static-demo"
spec:
  containers:
  - name: nginx-test
    image: nginx
    volumeMounts:
    - name: persistent-storage
      mountPath: /usr/share/nginx/html
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: efs-static-test
---
kind: Service
apiVersion: v1
metadata:
  name: nginx-lb-test
spec:
  type: LoadBalancer
  selector: # labels are used as selectors
    purpose: "efs-static-demo"
  ports:
  - protocol: TCP
    port: 80 # service port
    targetPort: 80
    nodePort: 30007